[v1]
"amdgpu_top 0.11.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["amdgpu_top"]
"bacon 3.22.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["bacon"]
"bandwhich 0.23.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bandwhich"]
"bat 0.26.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bat"]
"bingrep 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["bingrep"]
"bottom 0.12.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["btm"]
"broot 1.55.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["broot"]
"brotli 8.0.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "brotli",
    "catbrotli",
]
"cargo-audit 0.22.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-bloat 0.12.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-bloat"]
"cargo-cache 0.8.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-cache"]
"cargo-deb 3.6.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deb"]
"cargo-deny 0.19.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deny"]
"cargo-edit 0.13.8 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.121 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-outdated 0.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-outdated"]
"cargo-show 0.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-show"]
"cargo-udeps 0.1.60 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-update 18.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-install-update",
    "cargo-install-update-config",
]
"choose 1.3.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["choose"]
"counts 1.0.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["counts"]
"cw 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cw"]
"deno 2.2.11 (registry+https://github.com/rust-lang/crates.io-index)" = ["deno"]
"difftastic 0.67.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["difft"]
"du-dust 1.2.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["dust"]
"dysk 3.6.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["dysk"]
"evcxr_repl 0.21.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["evcxr"]
"eza 0.23.4 (registry+https://github.com/rust-lang/crates.io-index)" = ["eza"]
"fd-find 10.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["fd"]
"flamegraph 0.6.11 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-flamegraph",
    "flamegraph",
]
"git-delta 0.18.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["delta"]
"grex 1.4.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["grex"]
"htmlq 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["htmlq"]
"hx 0.7.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hx"]
"hyperfine 1.20.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["hyperfine"]
"imagecli 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["imagecli"]
"inferno 0.12.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "inferno-collapse-dtrace",
    "inferno-collapse-ghcprof",
    "inferno-collapse-guess",
    "inferno-collapse-perf",
    "inferno-collapse-recursive",
    "inferno-collapse-sample",
    "inferno-collapse-vsprof",
    "inferno-collapse-vtune",
    "inferno-collapse-xctrace",
    "inferno-diff-folded",
    "inferno-flamegraph",
]
"jless 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["jless"]
"jql 8.0.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["jql"]
"just 1.46.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["just"]
"legdur 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["legdur"]
"lemmeknow 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lemmeknow"]
"mdbook 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["mdbook"]
"neovide 0.15.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["neovide"]
"oxipng 10.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["oxipng"]
"pipr 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["pipr"]
"polars-cli 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["polars"]
"procs 0.14.10 (registry+https://github.com/rust-lang/crates.io-index)" = ["procs"]
"qsv 16.1.0 (path+file:///home/home/CLionProjects/qsv)" = ["qsv"]
"rargs 0.3.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rargs"]
"rav1e 0.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["rav1e"]
"ripgrep 15.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["rg"]
"sd 1.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sd"]
"skim 3.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["sk"]
"starship 1.24.2 (registry+https://github.com/rust-lang/crates.io-index)" = ["starship"]
"tantivy-cli 0.24.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tantivy"]
"tealdeer 1.8.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["tldr"]
"tokei 14.0.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["tokei"]
"tree-sitter-cli 0.26.5 (registry+https://github.com/rust-lang/crates.io-index)" = ["tree-sitter"]
"trippy 0.13.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trip"]
"twiggy 0.8.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["twiggy"]
"uwc 1.0.8 (registry+https://github.com/rust-lang/crates.io-index)" = ["uwc"]
"wasmtime-cli 41.0.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasmtime"]
"xh 0.25.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["xh"]
